### PR TITLE
Enable mono repo support by tweaking regexes to allow sub directories

### PR DESCRIPTION
**Pull request by mellisio**
Thanks taking the time to contribute. This template should help guide you through the process of creating a pull request for review. Please erase any part of this template that is not relevant to your pull request:

- [x] Have you followed the guidelines for [contributors](http://docs.libraries.io/contributorshandbook)?
- [x] Have you checked to ensure there aren't other open pull requests on the repository for a similar change?
- [x] Is there a corresponding ticket for your pull request?
- [x] Have you written new tests for your changes?
- [x] Have you successfully run the project with your changes locally?

### CODE REVIEW

**Comment by andrew** [comment]
@mellisio Looking good, only thing that I'm cautious of is picking up things embedded inside of vendored node_modules folders but I have a feeling that those will be filtered out elsewhere, just the removal of the tests makes me doubt myself.

**Comment by mellisio** [comment]
@andrew I was thinking, perhaps erroneously, that those folders shouldn't be included in git and wouldn't affect our use case since we do a git pull every time.

**Comment by andrew** [comment]
@mellisio usually they wouldn't but some people do include them to avoid depending on npmjs.org in production, which then throws a huge amount of extra manifest files into the repo

**Comment by andrew** [comment]
Checked this morning and `node_modules` and `bower_components` folders are ignored by the default configuration that I added a few months back.

Just released this as 6.3.0: https://rubygems.org/gems/bibliothecary/versions/6.3.0

**Pull request merged**
